-- 코드를 입력하세요
SELECT A.CAR_ID,A.CAR_TYPE, TRUNCATE(A.daily_fee * 30 * (1 - C.discount_rate * 0.01),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE 
WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
    AND C.duration_type = '30일 이상' 
    AND A.daily_fee * 30 * (1- C.discount_rate * 0.01) between 500000 and 2000000
GROUP BY A.CAR_ID
HAVING MAX(B.end_date)<="2022-11-01"
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;