-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",b.BOARD_ID,"/",FILE_ID,FILE_NAME, FILE_EXT)FILE_PATH
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_FILE F 
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;





